@server_url = https://subtle-definitely-kiwi.ngrok-free.app
# @server_url = http://localhost:1337

###
POST {{server_url}}/api/auth/local/register
Content-Type: application/json

{
  "username": "tomtom",
  "email": "thomaslaforge@gmail.com",
  "password": "admin1234"
}

###
POST {{server_url}}/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0b210b20iLCJlbWFpbCI6InRob21hc2xhZm9yZ2VAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wN1QwOTowODo1Mi43NzdaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wN1QwOToxMToxNC42MDdaIiwiaWF0IjoxNzAxOTQwMzIxfQ.tuzC-PVTqhF4qFaYOhC4wPxvK48EvNqtV-dh0moZLvI

{
  "currentPassword": "admin1234",
  "password": "tomtom1234",
  "passwordConfirmation": "tomtom1234"
}

###
POST {{server_url}}/api/auth/local
Content-Type: application/json

{
  "identifier": "thomaslaforge@gmail.com",
  "password": "tomtom1234"
}

###
POST {{server_url}}/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0b210b20iLCJlbWFpbCI6InRob21hc2xhZm9yZ2VAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wN1QwOTowODo1Mi43NzdaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wN1QwOToxMToxNC42MDdaIiwiaWF0IjoxNzAxOTQwMzIxfQ.tuzC-PVTqhF4qFaYOhC4wPxvK48EvNqtV-dh0moZLvI

###
GET {{server_url}}/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0b210b20iLCJlbWFpbCI6InRob21hc2xhZm9yZ2VAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wN1QwOTowODo1Mi43NzdaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wN1QwOToxMToxNC42MDdaIiwiaWF0IjoxNzAxOTQwMzIxfQ.tuzC-PVTqhF4qFaYOhC4wPxvK48EvNqtV-dh0moZLvI

###
GET {{server_url}}/api/products

###
POST {{server_url}}/api/products/check-exists
Content-Type: application/json

{
    "data": {
        "name": "Pepito",
        "description": "Des bons petits biscuits",
        "image": "https://images.openfoodfacts.org/images/products/304/828/290/0646/front_fr.54.400.jpg",
        "bar_code": "3048282900646"
    }
}   